#include "THISDUST.H"
#include "GAMEMENU.H"


// decompiled code
// original method signature: 
// void /*$ra*/ gamemenu_on__Fv()
 // line 48, offset 0x80077d20
	/* begin block 1 */
		// Start line: 49
		// Start offset: 0x80077D20
	/* end block 1 */
	// End offset: 0x80077D20
	// End Line: 49

	/* begin block 2 */
		// Start line: 106
	/* end block 2 */
	// End Line: 107

/* WARNING: Unknown calling convention yet parameter storage is locked */

void gamemenu_on__Fv(void)

{
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ gamemenu_off__Fv()
 // line 63, offset 0x80077d28
	/* begin block 1 */
		// Start line: 64
		// Start offset: 0x80077D28
	/* end block 1 */
	// End offset: 0x80077D28
	// End Line: 64

	/* begin block 2 */
		// Start line: 128
	/* end block 2 */
	// End Line: 129

/* WARNING: Unknown calling convention yet parameter storage is locked */

void gamemenu_off__Fv(void)

{
	return;
}





