#include "THISDUST.H"
#include "MISDAT.H"


// decompiled code
// original method signature: 
// void /*$ra*/ nullmissile__Fiiiiiicii(int mi /*$a0*/, int sx /*$a1*/, int sy /*$a2*/, int dx /*$a3*/, int dy /*stack 16*/, int midir /*stack 20*/, int mienemy /*stack 24*/, int id /*stack 28*/, int dam /*stack 32*/)
 // line 33, offset 0x80047b74
	/* begin block 1 */
		// Start line: 34
		// Start offset: 0x80047B74
	/* end block 1 */
	// End offset: 0x80047B74
	// End Line: 34

	/* begin block 2 */
		// Start line: 68
	/* end block 2 */
	// End Line: 69

void nullmissile__Fiiiiiicii
							 (int mi,int sx,int sy,int dx,int dy,int midir,int mienemy,int id,int dam)

{
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ FuncNULL__FP13MissileStructiii(struct MissileStruct *Ms /*$a0*/, int ScrX /*$a1*/, int ScrY /*$a2*/, int OtPos /*$a3*/)
 // line 806, offset 0x80047b7c
	/* begin block 1 */
		// Start line: 807
		// Start offset: 0x80047B7C
	/* end block 1 */
	// End offset: 0x80047B7C
	// End Line: 807

	/* begin block 2 */
		// Start line: 1614
	/* end block 2 */
	// End Line: 1615

void FuncNULL__FP13MissileStructiii(MissileStruct *Ms,int ScrX,int ScrY,int OtPos)

{
	return;
}





