#ifndef STORM_H
#define STORM_H


extern void Enter__9CCritSect(struct CCritSect *this); // 0x8003AA24


// decompiled code
// original method signature: 
// void /*$ra*/ Enter__9CCritSect(struct CCritSect *this /*$a0*/)
 // line 1104, offset 0x8003aa24
	/* begin block 1 */
		// Start line: 1105
		// Start offset: 0x8003AA24
	/* end block 1 */
	// End offset: 0x8003AA24
	// End Line: 1105

	/* begin block 2 */
		// Start line: 2208
	/* end block 2 */
	// End Line: 2209

void Enter__9CCritSect(CCritSect *this)

{
	return;
}





extern void * SMemAlloc(unsigned long bytes, char *filename, int linenumber, unsigned long flags); // 0x80073644

extern unsigned char SMemFree(void *ptr, char *filename, int linenumber, unsigned long flags); // 0x80073664


#endif
