#include "THISDUST.H"
#include "TESTCODE.H"


// decompiled code
// original method signature: 
// void /*$ra*/ DoGameTestStuff__Fv()
 // line 66, offset 0x800735e4
	/* begin block 1 */
		// Start line: 67
		// Start offset: 0x800735E4
	/* end block 1 */
	// End offset: 0x80073600
	// End Line: 70

	/* begin block 2 */
		// Start line: 132
	/* end block 2 */
	// End Line: 133

/* WARNING: Unknown calling convention yet parameter storage is locked */

void DoGameTestStuff__Fv(void)

{
	GRL_InitGwin__Fv();
	StartGame__FUcUc('\x01','\x01');
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ DoInitGameStuff__Fv()
 // line 73, offset 0x80073610
	/* begin block 1 */
		// Start line: 74
		// Start offset: 0x80073610
	/* end block 1 */
	// End offset: 0x80073634
	// End Line: 77

	/* begin block 2 */
		// Start line: 146
	/* end block 2 */
	// End Line: 147

/* WARNING: Unknown calling convention yet parameter storage is locked */

void DoInitGameStuff__Fv(void)

{
	GRL_InitGwin__Fv();
	alloc_plr__Fv();
	LittleStart__FUcUc('\x01','\x01');
	return;
}





