#ifndef BLOCK_H
#define BLOCK_H


typedef int (*TDRFuncPtr_IterateVisibleMap__7CBlocksiiPFP9CacheInfoP8map_infoii_ib3Func)();

extern void InitFromGt4__9LittleGt4P8POLY_GT4ii(struct LittleGt4 *this, struct POLY_GT4 *Gt4, int nw, int nh); // 0x80091CF8

extern int GetMaxOtPos__7CBlocks(); // 0x800894A4

extern int GetMaxOtPos__7CBlocks(); // 0x80098948

extern int GetMaxOtPos__7CBlocks(); // 0x800376F4

extern int GetMaxOtPos__7CBlocks(); // 0x8007F34C

extern int GetMaxOtPos__7CBlocks(); // 0x80082698

extern int GetOverlayOtBase__7CBlocks(); // 0x8008949C

extern int GetOverlayOtBase__7CBlocks(); // 0x8008ACDC

extern int GetOverlayOtBase__7CBlocks(); // 0x8009DCA8

extern int GetOverlayOtBase__7CBlocks(); // 0x800A432C

extern int GetOverlayOtBase__7CBlocks(); // 0x800A4FDC

extern int GetOverlayOtBase__7CBlocks(); // 0x800A68C8

extern int GetOverlayOtBase__7CBlocks(); // 0x800AB68C

extern int GetOverlayOtBase__7CBlocks(); // 0x800AF080

extern int GetOverlayOtBase__7CBlocks(); // 0x800B02EC

extern int GetOverlayOtBase__7CBlocks(); // 0x800376EC

extern int GetOverlayOtBase__7CBlocks(); // 0x8004EA5C

extern int GetOverlayOtBase__7CBlocks(); // 0x80069314

extern int GetOverlayOtBase__7CBlocks(); // 0x80074470

extern int GetOverlayOtBase__7CBlocks(); // 0x80082690

extern int GetOtPos__7CBlocksi(struct CBlocks *this, int LogicalY); // 0x80091CC0

extern int GetOtPos__7CBlocksi(struct CBlocks *this, int LogicalY); // 0x80096760

extern int GetOtPos__7CBlocksi(struct CBlocks *this, int LogicalY); // 0x800A0984

extern int GetOtPos__7CBlocksi(struct CBlocks *this, int LogicalY); // 0x800ACF1C

extern int GetOtPos__7CBlocksi(struct CBlocks *this, int LogicalY); // 0x8005FB90

extern void MoveToScrollTarget__7CBlocks(struct CBlocks *this); // 0x8009C534

extern void MoveToScrollTarget__7CBlocks(struct CBlocks *this); // 0x8007B0E4

extern void SetTown__7CBlocksb(struct CBlocks *this, void * Val); // 0x8009C52C

extern void DumpMonsters__7CBlocks(struct CBlocks *this); // 0x80091C98

extern void DumpMonsters__7CBlocks(struct CBlocks *this); // 0x800ADF34

extern void DumpObjs__7CBlocks(struct CBlocks *this); // 0x80091C74

extern void DumpItems__7CBlocks(struct CBlocks *this); // 0x80091C50

extern void SetObjGraphics__7CBlocksi(struct CBlocks *this, int Id); // 0x80091C28

extern void SetItemGraphics__7CBlocksi(struct CBlocks *this, int Id); // 0x80091C00


// decompiled code
// original method signature: 
// void /*$ra*/ InitFromGt4__9LittleGt4P8POLY_GT4ii(struct LittleGt4 *this /*$a0*/, struct POLY_GT4 *Gt4 /*$a1*/, int nw /*$a2*/, int nh /*$a3*/)
 // line 56, offset 0x80091cf8
	/* begin block 1 */
		// Start line: 57
		// Start offset: 0x80091CF8
	/* end block 1 */
	// End offset: 0x80091D7C
	// End Line: 70

	/* begin block 2 */
		// Start line: 113
	/* end block 2 */
	// End Line: 114

void InitFromGt4__9LittleGt4P8POLY_GT4ii(LittleGt4 *this,POLY_GT4 *Gt4,int nw,int nh)

{
	uchar uVar1;
	
	this->clut = Gt4->clut;
	this->tpage = Gt4->tpage;
	this->code = Gt4->code;
	this->u0 = Gt4->u0;
	this->v0 = Gt4->v0;
	this->u1 = Gt4->u1;
	this->v1 = Gt4->v1;
	this->u2 = Gt4->u2;
	this->v2 = Gt4->v2;
	this->u3 = Gt4->u3;
	uVar1 = Gt4->v3;
	this->w = (uchar)nw;
	this->h = (uchar)nh;
	this->v3 = uVar1;
	return;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetMaxOtPos__7CBlocks()
 // line 171, offset 0x800894a4
	/* begin block 1 */
		// Start line: 172
		// Start offset: 0x800894A4
	/* end block 1 */
	// End offset: 0x800894A4
	// End Line: 172

	/* begin block 2 */
		// Start line: 342
	/* end block 2 */
	// End Line: 343

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetMaxOtPos__7CBlocks(void)

{
	return 0x1ff;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetMaxOtPos__7CBlocks()
 // line 171, offset 0x80098948
	/* begin block 1 */
		// Start line: 172
		// Start offset: 0x80098948
	/* end block 1 */
	// End offset: 0x80098948
	// End Line: 172

	/* begin block 2 */
		// Start line: 342
	/* end block 2 */
	// End Line: 343

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetMaxOtPos__7CBlocks(void)

{
	return 0x1ff;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetMaxOtPos__7CBlocks()
 // line 171, offset 0x800376f4
	/* begin block 1 */
		// Start line: 172
		// Start offset: 0x800376F4
	/* end block 1 */
	// End offset: 0x800376F4
	// End Line: 172

	/* begin block 2 */
		// Start line: 342
	/* end block 2 */
	// End Line: 343

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetMaxOtPos__7CBlocks(void)

{
	return 0x1ff;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetMaxOtPos__7CBlocks()
 // line 171, offset 0x8007f34c
	/* begin block 1 */
		// Start line: 172
		// Start offset: 0x8007F34C
	/* end block 1 */
	// End offset: 0x8007F34C
	// End Line: 172

	/* begin block 2 */
		// Start line: 342
	/* end block 2 */
	// End Line: 343

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetMaxOtPos__7CBlocks(void)

{
	return 0x1ff;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetMaxOtPos__7CBlocks()
 // line 171, offset 0x80082698
	/* begin block 1 */
		// Start line: 172
		// Start offset: 0x80082698
	/* end block 1 */
	// End offset: 0x80082698
	// End Line: 172

	/* begin block 2 */
		// Start line: 342
	/* end block 2 */
	// End Line: 343

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetMaxOtPos__7CBlocks(void)

{
	return 0x1ff;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOverlayOtBase__7CBlocks()
 // line 174, offset 0x8008949c
	/* begin block 1 */
		// Start line: 175
		// Start offset: 0x8008949C
	/* end block 1 */
	// End offset: 0x8008949C
	// End Line: 175

	/* begin block 2 */
		// Start line: 348
	/* end block 2 */
	// End Line: 349

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOverlayOtBase__7CBlocks(void)

{
	return 0x1e8;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOverlayOtBase__7CBlocks()
 // line 174, offset 0x8008acdc
	/* begin block 1 */
		// Start line: 175
		// Start offset: 0x8008ACDC
	/* end block 1 */
	// End offset: 0x8008ACDC
	// End Line: 175

	/* begin block 2 */
		// Start line: 348
	/* end block 2 */
	// End Line: 349

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOverlayOtBase__7CBlocks(void)

{
	return 0x1e8;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOverlayOtBase__7CBlocks()
 // line 174, offset 0x8009dca8
	/* begin block 1 */
		// Start line: 175
		// Start offset: 0x8009DCA8
	/* end block 1 */
	// End offset: 0x8009DCA8
	// End Line: 175

	/* begin block 2 */
		// Start line: 348
	/* end block 2 */
	// End Line: 349

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOverlayOtBase__7CBlocks(void)

{
	return 0x1e8;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOverlayOtBase__7CBlocks()
 // line 174, offset 0x800a432c
	/* begin block 1 */
		// Start line: 175
		// Start offset: 0x800A432C
	/* end block 1 */
	// End offset: 0x800A432C
	// End Line: 175

	/* begin block 2 */
		// Start line: 348
	/* end block 2 */
	// End Line: 349

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOverlayOtBase__7CBlocks(void)

{
	return 0x1e8;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOverlayOtBase__7CBlocks()
 // line 174, offset 0x800a4fdc
	/* begin block 1 */
		// Start line: 175
		// Start offset: 0x800A4FDC
	/* end block 1 */
	// End offset: 0x800A4FDC
	// End Line: 175

	/* begin block 2 */
		// Start line: 348
	/* end block 2 */
	// End Line: 349

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOverlayOtBase__7CBlocks(void)

{
	return 0x1e8;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOverlayOtBase__7CBlocks()
 // line 174, offset 0x800a68c8
	/* begin block 1 */
		// Start line: 175
		// Start offset: 0x800A68C8
	/* end block 1 */
	// End offset: 0x800A68C8
	// End Line: 175

	/* begin block 2 */
		// Start line: 348
	/* end block 2 */
	// End Line: 349

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOverlayOtBase__7CBlocks(void)

{
	return 0x1e8;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOverlayOtBase__7CBlocks()
 // line 174, offset 0x800ab68c
	/* begin block 1 */
		// Start line: 175
		// Start offset: 0x800AB68C
	/* end block 1 */
	// End offset: 0x800AB68C
	// End Line: 175

	/* begin block 2 */
		// Start line: 348
	/* end block 2 */
	// End Line: 349

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOverlayOtBase__7CBlocks(void)

{
	return 0x1e8;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOverlayOtBase__7CBlocks()
 // line 174, offset 0x800af080
	/* begin block 1 */
		// Start line: 175
		// Start offset: 0x800AF080
	/* end block 1 */
	// End offset: 0x800AF080
	// End Line: 175

	/* begin block 2 */
		// Start line: 348
	/* end block 2 */
	// End Line: 349

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOverlayOtBase__7CBlocks(void)

{
	return 0x1e8;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOverlayOtBase__7CBlocks()
 // line 174, offset 0x800b02ec
	/* begin block 1 */
		// Start line: 175
		// Start offset: 0x800B02EC
	/* end block 1 */
	// End offset: 0x800B02EC
	// End Line: 175

	/* begin block 2 */
		// Start line: 348
	/* end block 2 */
	// End Line: 349

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOverlayOtBase__7CBlocks(void)

{
	return 0x1e8;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOverlayOtBase__7CBlocks()
 // line 174, offset 0x800376ec
	/* begin block 1 */
		// Start line: 175
		// Start offset: 0x800376EC
	/* end block 1 */
	// End offset: 0x800376EC
	// End Line: 175

	/* begin block 2 */
		// Start line: 348
	/* end block 2 */
	// End Line: 349

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOverlayOtBase__7CBlocks(void)

{
	return 0x1e8;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOverlayOtBase__7CBlocks()
 // line 174, offset 0x8004ea5c
	/* begin block 1 */
		// Start line: 175
		// Start offset: 0x8004EA5C
	/* end block 1 */
	// End offset: 0x8004EA5C
	// End Line: 175

	/* begin block 2 */
		// Start line: 348
	/* end block 2 */
	// End Line: 349

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOverlayOtBase__7CBlocks(void)

{
	return 0x1e8;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOverlayOtBase__7CBlocks()
 // line 174, offset 0x80069314
	/* begin block 1 */
		// Start line: 175
		// Start offset: 0x80069314
	/* end block 1 */
	// End offset: 0x80069314
	// End Line: 175

	/* begin block 2 */
		// Start line: 348
	/* end block 2 */
	// End Line: 349

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOverlayOtBase__7CBlocks(void)

{
	return 0x1e8;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOverlayOtBase__7CBlocks()
 // line 174, offset 0x80074470
	/* begin block 1 */
		// Start line: 175
		// Start offset: 0x80074470
	/* end block 1 */
	// End offset: 0x80074470
	// End Line: 175

	/* begin block 2 */
		// Start line: 348
	/* end block 2 */
	// End Line: 349

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOverlayOtBase__7CBlocks(void)

{
	return 0x1e8;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOverlayOtBase__7CBlocks()
 // line 174, offset 0x80082690
	/* begin block 1 */
		// Start line: 175
		// Start offset: 0x80082690
	/* end block 1 */
	// End offset: 0x80082690
	// End Line: 175

	/* begin block 2 */
		// Start line: 348
	/* end block 2 */
	// End Line: 349

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOverlayOtBase__7CBlocks(void)

{
	return 0x1e8;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOtPos__7CBlocksi(struct CBlocks *this /*$a0*/, int LogicalY /*$a1*/)
 // line 177, offset 0x80091cc0
	/* begin block 1 */
		// Start line: 178
		// Start offset: 0x80091CC0
		// Variables:
	// 		int OtPos; // $v1
	/* end block 1 */
	// End offset: 0x80091CF0
	// End Line: 189

	/* begin block 2 */
		// Start line: 355
	/* end block 2 */
	// End Line: 356

int GetOtPos__7CBlocksi(CBlocks *this,int LogicalY)

{
	int iVar1;
	int iVar2;
	
	iVar1 = (int)(this->ClipRect).y + LogicalY + PosAdj;
	iVar2 = iVar1;
	if (iVar1 < -0x43) {
		iVar2 = -0x43;
	}
	if (0x19b < iVar1) {
		iVar2 = 0x19b;
	}
	return iVar2 + 0x4d;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOtPos__7CBlocksi(struct CBlocks *this /*$a0*/, int LogicalY /*$a1*/)
 // line 177, offset 0x80096760
	/* begin block 1 */
		// Start line: 178
		// Start offset: 0x80096760
		// Variables:
	// 		int OtPos; // $v1
	/* end block 1 */
	// End offset: 0x80096794
	// End Line: 189

	/* begin block 2 */
		// Start line: 355
	/* end block 2 */
	// End Line: 356

int GetOtPos__7CBlocksi(CBlocks *this,int LogicalY)

{
	int iVar1;
	int iVar2;
	
	iVar1 = (int)(this->ClipRect).y + LogicalY + PosAdj;
	iVar2 = iVar1;
	if (iVar1 < -0x43) {
		iVar2 = -0x43;
	}
	if (0x19b < iVar1) {
		iVar2 = 0x19b;
	}
	return iVar2 + 0x4d;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOtPos__7CBlocksi(struct CBlocks *this /*$a0*/, int LogicalY /*$a1*/)
 // line 177, offset 0x800a0984
	/* begin block 1 */
		// Start line: 178
		// Start offset: 0x800A0984
		// Variables:
	// 		int OtPos; // $v1
	/* end block 1 */
	// End offset: 0x800A09B8
	// End Line: 189

	/* begin block 2 */
		// Start line: 355
	/* end block 2 */
	// End Line: 356

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOtPos__7CBlocksi(CBlocks *this,int LogicalY)

{
	int iVar1;
	int iVar2;
	
	iVar1 = (int)(this->ClipRect).y + LogicalY + PosAdj;
	iVar2 = iVar1;
	if (iVar1 < -0x43) {
		iVar2 = -0x43;
	}
	if (0x19b < iVar1) {
		iVar2 = 0x19b;
	}
	return iVar2 + 0x4d;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOtPos__7CBlocksi(struct CBlocks *this /*$a0*/, int LogicalY /*$a1*/)
 // line 177, offset 0x800acf1c
	/* begin block 1 */
		// Start line: 178
		// Start offset: 0x800ACF1C
		// Variables:
	// 		int OtPos; // $v1
	/* end block 1 */
	// End offset: 0x800ACF50
	// End Line: 189

	/* begin block 2 */
		// Start line: 355
	/* end block 2 */
	// End Line: 356

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOtPos__7CBlocksi(CBlocks *this,int LogicalY)

{
	int iVar1;
	int iVar2;
	
	iVar1 = (int)(this->ClipRect).y + LogicalY + PosAdj;
	iVar2 = iVar1;
	if (iVar1 < -0x43) {
		iVar2 = -0x43;
	}
	if (0x19b < iVar1) {
		iVar2 = 0x19b;
	}
	return iVar2 + 0x4d;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GetOtPos__7CBlocksi(struct CBlocks *this /*$a0*/, int LogicalY /*$a1*/)
 // line 177, offset 0x8005fb90
	/* begin block 1 */
		// Start line: 178
		// Start offset: 0x8005FB90
		// Variables:
	// 		int OtPos; // $v1
	/* end block 1 */
	// End offset: 0x8005FBC4
	// End Line: 189

	/* begin block 2 */
		// Start line: 355
	/* end block 2 */
	// End Line: 356

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GetOtPos__7CBlocksi(CBlocks *this,int LogicalY)

{
	int iVar1;
	int iVar2;
	
	iVar1 = (int)(this->ClipRect).y + LogicalY + PosAdj;
	iVar2 = iVar1;
	if (iVar1 < -0x43) {
		iVar2 = -0x43;
	}
	if (0x19b < iVar1) {
		iVar2 = 0x19b;
	}
	return iVar2 + 0x4d;
}



// decompiled code
// original method signature: 
// void /*$ra*/ MoveToScrollTarget__7CBlocks(struct CBlocks *this /*$a0*/)
 // line 205, offset 0x8009c534
	/* begin block 1 */
		// Start line: 206
		// Start offset: 0x8009C534
	/* end block 1 */
	// End offset: 0x8009C540
	// End Line: 206

	/* begin block 2 */
		// Start line: 410
	/* end block 2 */
	// End Line: 411

void MoveToScrollTarget__7CBlocks(CBlocks *this)

{
	this->Mx = this->StX;
	this->My = this->StY;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ MoveToScrollTarget__7CBlocks(struct CBlocks *this /*$a0*/)
 // line 205, offset 0x8007b0e4
	/* begin block 1 */
		// Start line: 206
		// Start offset: 0x8007B0E4
	/* end block 1 */
	// End offset: 0x8007B0F0
	// End Line: 206

	/* begin block 2 */
		// Start line: 410
	/* end block 2 */
	// End Line: 411

/* WARNING: Unknown calling convention yet parameter storage is locked */

void MoveToScrollTarget__7CBlocks(CBlocks *this)

{
	this->Mx = this->StX;
	this->My = this->StY;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetTown__7CBlocksb(struct CBlocks *this /*$a0*/, void * Val /*$a1*/)
 // line 212, offset 0x8009c52c
	/* begin block 1 */
		// Start line: 213
		// Start offset: 0x8009C52C
	/* end block 1 */
	// End offset: 0x8009C52C
	// End Line: 213

	/* begin block 2 */
		// Start line: 424
	/* end block 2 */
	// End Line: 425

void SetTown__7CBlocksb(CBlocks *this,void *Val)

{
	this->IsTown = Val;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ DumpMonsters__7CBlocks(struct CBlocks *this /*$a0*/)
 // line 228, offset 0x80091c98
	/* begin block 1 */
		// Start line: 229
		// Start offset: 0x80091C98
	/* end block 1 */
	// End offset: 0x80091CB0
	// End Line: 229

	/* begin block 2 */
		// Start line: 456
	/* end block 2 */
	// End Line: 457

void DumpMonsters__7CBlocks(CBlocks *this)

{
	this->MonsterList = (MonstList *)0x0;
	DumpGraphics__7CBlocksPP7TextDatPi(this,&this->MonstTexDat,&this->MonstTexId);
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ DumpMonsters__7CBlocks(struct CBlocks *this /*$a0*/)
 // line 228, offset 0x800adf34
	/* begin block 1 */
		// Start line: 229
		// Start offset: 0x800ADF34
	/* end block 1 */
	// End offset: 0x800ADF4C
	// End Line: 229

	/* begin block 2 */
		// Start line: 456
	/* end block 2 */
	// End Line: 457

/* WARNING: Unknown calling convention yet parameter storage is locked */

void DumpMonsters__7CBlocks(CBlocks *this)

{
	this->MonsterList = (MonstList *)0x0;
	DumpGraphics__7CBlocksPP7TextDatPi(this,&this->MonstTexDat,&this->MonstTexId);
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ DumpObjs__7CBlocks(struct CBlocks *this /*$a0*/)
 // line 229, offset 0x80091c74
	/* begin block 1 */
		// Start line: 230
		// Start offset: 0x80091C74
	/* end block 1 */
	// End offset: 0x80091C88
	// End Line: 230

	/* begin block 2 */
		// Start line: 458
	/* end block 2 */
	// End Line: 459

void DumpObjs__7CBlocks(CBlocks *this)

{
	DumpGraphics__7CBlocksPP7TextDatPi(this,&this->ObjTexDat,&this->ObjTexId);
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ DumpItems__7CBlocks(struct CBlocks *this /*$a0*/)
 // line 230, offset 0x80091c50
	/* begin block 1 */
		// Start line: 231
		// Start offset: 0x80091C50
	/* end block 1 */
	// End offset: 0x80091C64
	// End Line: 231

	/* begin block 2 */
		// Start line: 460
	/* end block 2 */
	// End Line: 461

void DumpItems__7CBlocks(CBlocks *this)

{
	DumpGraphics__7CBlocksPP7TextDatPi(this,&this->ItemTexDat,&this->ItemTexId);
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetObjGraphics__7CBlocksi(struct CBlocks *this /*$a0*/, int Id /*$a3*/)
 // line 260, offset 0x80091c28
	/* begin block 1 */
		// Start line: 261
		// Start offset: 0x80091C28
	/* end block 1 */
	// End offset: 0x80091C40
	// End Line: 261

	/* begin block 2 */
		// Start line: 520
	/* end block 2 */
	// End Line: 521

void SetObjGraphics__7CBlocksi(CBlocks *this,int Id)

{
	SetGraphics__7CBlocksPP7TextDatPii(this,&this->ObjTexDat,&this->ObjTexId,Id);
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetItemGraphics__7CBlocksi(struct CBlocks *this /*$a0*/, int Id /*$a3*/)
 // line 261, offset 0x80091c00
	/* begin block 1 */
		// Start line: 262
		// Start offset: 0x80091C00
	/* end block 1 */
	// End offset: 0x80091C18
	// End Line: 262

	/* begin block 2 */
		// Start line: 522
	/* end block 2 */
	// End Line: 523

void SetItemGraphics__7CBlocksi(CBlocks *this,int Id)

{
	SetGraphics__7CBlocksPP7TextDatPii(this,&this->ItemTexDat,&this->ItemTexId,Id);
	return;
}





extern int GetHighlightCol__FiPcUsUsUs(int Index, char *SelList, unsigned short P1Col, unsigned short P2Col, int P12Col); // 0x800919F8

extern int GetHighlightCol__FiPiUsUsUs(int Index, int *SelList, unsigned short P1Col, unsigned short P2Col, int P12Col); // 0x80091ABC

extern int GetCreature__14TownToCreaturei(struct TownToCreature *this, int GameCreature); // 0x80091BE4

extern void UpdateSel__FPUsUsPUc(unsigned short *Col, unsigned short Add, unsigned char *Count); // 0x8008D41C

extern void CycleSelCols__Fv(); // 0x8008D45C

extern int FindTownCreature__7CBlocksi(struct CBlocks *this, int GameEqu); // 0x8008D614

extern int FindCreature__7CBlocksi(struct CBlocks *this, int MgNum); // 0x8008D688

extern struct CBlocks * __7CBlocksiiiii(struct CBlocks *this, int BgId, int ObjId, int ItemId, int Level, int List); // 0x8008D6FC

extern void SetTownersGraphics__7CBlocks(struct CBlocks *this); // 0x8008D860

extern void SetMonsterGraphics__7CBlocksii(struct CBlocks *this, int Level, int List); // 0x8008D898

extern void _._7CBlocks(struct CBlocks *this, int __in_chrg); // 0x8008D960

extern void DumpGt4s__7CBlocks(struct CBlocks *this); // 0x8008D9E8

extern void DumpRects__7CBlocks(struct CBlocks *this); // 0x8008DA50

extern void SetGraphics__7CBlocksPP7TextDatPii(struct CBlocks *this, struct TextDat **TDat, int *pId, int Id); // 0x8008DAB8

extern void DumpGraphics__7CBlocksPP7TextDatPi(struct CBlocks *this, struct TextDat **TDat, int *Id); // 0x8008DB14

extern void Load__7CBlocksi(struct CBlocks *this, int Id); // 0x8008DB64

extern void MakeRectTable__7CBlocks(struct CBlocks *this); // 0x8008DC1C

extern void MakeGt4Table__7CBlocks(struct CBlocks *this); // 0x8008DD70

extern void MakeGt4__7CBlocksP8POLY_GT4P9FRAME_HDR(struct CBlocks *this, struct POLY_GT4 *GT4, struct FRAME_HDR *Fr); // 0x8008DF54

extern void MyRoutine__FR7CBlocksii(struct CBlocks *B, int x, int y); // 0x8008E07C

extern void SetRandOffset__7CBlocksi(struct CBlocks *this, int QuakeAmount); // 0x8008E0E4

extern void Print__7CBlocks(struct CBlocks *this); // 0x8008E140

extern void SetXY__7CBlocksii(struct CBlocks *this, int nx, int ny); // 0x8008E25C

extern void GetXY__7CBlocksPiT1(struct CBlocks *this, int *nx, int *ny); // 0x8008E284

extern void InitColourCycling__7CBlocks(struct CBlocks *this); // 0x8008E29C

extern void GetGCol__7CBlocksiiPUcP7RGBData(struct CBlocks *this, int x, int y, unsigned char *Rgb, struct RGBData *Data); // 0x8008E3E8

extern void PrintMap__7CBlocksii(struct CBlocks *this, int x, int y); // 0x8008E528

extern void IterateVisibleMap__7CBlocksiiPFP9CacheInfoP8map_infoii_ib(struct CBlocks *this, int x, int y, TDRFuncPtr_IterateVisibleMap__7CBlocksiiPFP9CacheInfoP8map_infoii_ib3Func Func, void * VisCheck); // 0x8008F098

extern int AddMonst__FP9CacheInfoP8map_infoii(struct CacheInfo *Info, struct map_info *p0, int bx, int by); // 0x8008F510

extern void PrintMonsters__7CBlocksii(struct CBlocks *this, int x, int y); // 0x8008F5F8

extern int AddTowners__FP9CacheInfoP8map_infoii(struct CacheInfo *Info, struct map_info *p0, int bx, int by); // 0x8009009C

extern void PrintTowners__7CBlocksii(struct CBlocks *this, int x, int y); // 0x800900F8

extern int AddObject__FP9CacheInfoP8map_infoii(struct CacheInfo *Info, struct map_info *p0, int bx, int by); // 0x800904B0

extern void PrintObjects__7CBlocksii(struct CBlocks *this, int x, int y); // 0x8009050C

extern int AddDead__FP9CacheInfoP8map_infoii(struct CacheInfo *Info, struct map_info *p0, int bx, int by); // 0x80090968

extern void PrintDead__7CBlocksii(struct CBlocks *this, int x, int y); // 0x800909F4

extern int AddItem__FP9CacheInfoP8map_infoii(struct CacheInfo *Info, struct map_info *p0, int bx, int by); // 0x80090CB8

extern void PrintItems__7CBlocksii(struct CBlocks *this, int x, int y); // 0x80090D14

extern int AddMissile__FP9CacheInfoP8map_infoii(struct CacheInfo *Info, struct map_info *p0, int bx, int by); // 0x800912D4

extern void PrintMissiles__7CBlocksii(struct CBlocks *this, int x, int y); // 0x800913EC

extern int ScrToWorldX__7CBlocksii(struct CBlocks *this, int sx, int sy); // 0x800915E4

extern int ScrToWorldY__7CBlocksii(struct CBlocks *this, int sx, int sy); // 0x800915F8

extern void SetScrollTarget__7CBlocksii(struct CBlocks *this, int x, int y); // 0x8009160C

extern void DoScroll__7CBlocks(struct CBlocks *this); // 0x800916D0

extern void SetPlayerPosBlocks__7CBlocksiii(struct CBlocks *this, int PlayerNum, int bx, int by); // 0x800917BC

extern void GetScrXY__7CBlocksR4RECTiiii(struct CBlocks *this, struct RECT *R, int x, int y, int sxoff, int syoff); // 0x8009185C

extern void ShadScaleSkew__7CBlocksP8POLY_FT4(struct POLY_FT4 *Ft4); // 0x80091930

extern int WorldToScrX__7CBlocksii(struct CBlocks *this, int x, int y); // 0x800919D0

extern int WorldToScrY__7CBlocksii(struct CBlocks *this, int x, int y); // 0x800919D8

extern struct CBlocks * BL_GetCurrentBlocks__Fv(); // 0x800919EC


#endif
