#include "THISDUST.H"
#include "LAMBO.H"


// decompiled code
// original method signature: 
// void /*$ra*/ StevesDummyPoll__Fv()
 // line 73, offset 0x80095844
	/* begin block 1 */
		// Start line: 74
		// Start offset: 0x80095844
	/* end block 1 */
	// End offset: 0x80095844
	// End Line: 74

	/* begin block 2 */
		// Start line: 147
	/* end block 2 */
	// End Line: 148

/* WARNING: Unknown calling convention yet parameter storage is locked */

void StevesDummyPoll__Fv(void)

{
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ Lambo__Fv()
 // line 77, offset 0x8009584c
	/* begin block 1 */
		// Start line: 78
		// Start offset: 0x8009584C
	/* end block 1 */
	// End offset: 0x8009584C
	// End Line: 79

	/* begin block 2 */
		// Start line: 157
	/* end block 2 */
	// End Line: 158

/* WARNING: Unknown calling convention yet parameter storage is locked */

void Lambo__Fv(void)

{
	return;
}





