#include "THISDUST.H"
#include "MEM.H"


// decompiled code
// original method signature: 
// void /*$ra*/ MyFilter__FUlUlPCc(unsigned long MemType /*$a0*/, unsigned long Size /*$a1*/, char *Name /*$a2*/)
 // line 96, offset 0x80084424
	/* begin block 1 */
		// Start line: 97
		// Start offset: 0x80084424
	/* end block 1 */
	// End offset: 0x80084424
	// End Line: 97

void MyFilter__FUlUlPCc(ulong MemType,ulong Size,char *Name)

{
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SlowMemMove__FPvT0Ul(void *Dest /*$a0*/, void *Source /*$a1*/, unsigned long size /*$a2*/)
 // line 150, offset 0x8008442c
	/* begin block 1 */
		// Start line: 151
		// Start offset: 0x8008442C
	/* end block 1 */
	// End offset: 0x8008443C
	// End Line: 152

	/* begin block 2 */
		// Start line: 300
	/* end block 2 */
	// End Line: 301

void SlowMemMove__FPvT0Ul(void *Dest,void *Source,ulong size)

{
	memmove(Dest,Source,size);
	return;
}





