#include "THISDUST.H"
#include "MONSVIEW.H"


// decompiled code
// original method signature: 
// void /*$ra*/ DisplayMonsterTypes__Fv()
 // line 232, offset 0x800af0e8
	/* begin block 1 */
		// Start line: 233
		// Start offset: 0x800AF0E8
	/* end block 1 */
	// End offset: 0x800AF0E8
	// End Line: 233

	/* begin block 2 */
		// Start line: 465
	/* end block 2 */
	// End Line: 466

/* WARNING: Unknown calling convention yet parameter storage is locked */

void DisplayMonsterTypes__Fv(void)

{
	return;
}





