#ifndef OVERINFO_H
#define OVERINFO_H


extern void OVR_LoadAddress() ; // 0x8010DBAC

extern void OVR_FrontEndAddress() ; // 0x8010DBB0

extern void OVR_PregameAddress() ; // 0x8010DBB4

extern void OVR_GameAddress() ; // 0x8010DBB8

extern void OVR_MemCardAddress() ; // 0x8010DBBC

extern void OVR_FmvAddress() ; // 0x8010DBC0

extern void OVR_FrontEndSize() ; // 0x8010DBC4

extern void OVR_PregameSize() ; // 0x8010DBC8

extern void OVR_GameSize() ; // 0x8010DBCC

extern void OVR_MemCardSize() ; // 0x8010DBD0

extern void OVR_FmvSize() ; // 0x8010DBD4

extern void OPT_RamSize() ; // 0x8010DBD8


#endif
