#include "THISDUST.H"
#include "PREGAME.H"


// decompiled code
// original method signature: 
// void /*$ra*/ PreGameOnlyTestRoutine__Fv()
 // line 62, offset 0x80139bfc
	/* begin block 1 */
		// Start line: 63
		// Start offset: 0x80139BFC
	/* end block 1 */
	// End offset: 0x80139C14
	// End Line: 64

	/* begin block 2 */
		// Start line: 124
	/* end block 2 */
	// End Line: 125

/* WARNING: Unknown calling convention yet parameter storage is locked */

void PreGameOnlyTestRoutine__Fv(void)

{
	DBG_SendMessage("You shouldn\'t get here");
	return;
}





