#include "THISDUST.H"
#include "PRESONLY.H"


// decompiled code
// original method signature: 
// void /*$ra*/ PresOnlyTestRoutine__Fv()
 // line 60, offset 0x80139bfc
	/* begin block 1 */
		// Start line: 61
		// Start offset: 0x80139BFC
	/* end block 1 */
	// End offset: 0x80139C14
	// End Line: 62

	/* begin block 2 */
		// Start line: 120
	/* end block 2 */
	// End Line: 121

/* WARNING: Unknown calling convention yet parameter storage is locked */

void PresOnlyTestRoutine__Fv(void)

{
	DBG_SendMessage("You shouldn\'t get here");
	return;
}





