#include "THISDUST.H"
#include "MISDAT.H"


// decompiled code
// original method signature: 
// void /*$ra*/ nullmissile__Fiiiiiicii(int mi /*$a0*/, int sx /*$a1*/, int sy /*$a2*/, int dx /*$a3*/, int dy /*stack 16*/, int midir /*stack 20*/, int mienemy /*stack 24*/, int id /*stack 28*/, int dam /*stack 32*/)
 // line 33, offset 0x8004ea8c
	/* begin block 1 */
		// Start line: 34
		// Start offset: 0x8004EA8C
	/* end block 1 */
	// End offset: 0x8004EA8C
	// End Line: 34

	/* begin block 2 */
		// Start line: 68
	/* end block 2 */
	// End Line: 69

/* WARNING: Unknown calling convention yet parameter storage is locked */

void nullmissile__Fiiiiiicii
							 (int mi,int sx,int sy,int dx,int dy,int midir,int mienemy,int id,int dam)

{
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ FuncNULL__FP13MissileStructiii(struct MissileStruct *Ms /*$a0*/, int ScrX /*$a1*/, int ScrY /*$a2*/, int OtPos /*$a3*/)
 // line 812, offset 0x8004ea94
	/* begin block 1 */
		// Start line: 813
		// Start offset: 0x8004EA94
	/* end block 1 */
	// End offset: 0x8004EA94
	// End Line: 813

	/* begin block 2 */
		// Start line: 1626
	/* end block 2 */
	// End Line: 1627

/* WARNING: Unknown calling convention yet parameter storage is locked */

void FuncNULL__FP13MissileStructiii(MissileStruct *Ms,int ScrX,int ScrY,int OtPos)

{
	return;
}





