#ifndef PRETRIGS_H
#define PRETRIGS_H


extern void InitNoTriggers__Fv(); // 0x801621AC

extern void InitTownTriggers__Fv(); // 0x801621D0

extern void InitL1Triggers__Fv(); // 0x80162530

extern void InitL2Triggers__Fv(); // 0x8016265C

extern void InitL3Triggers__Fv(); // 0x80162824

extern void InitL4Triggers__Fv(); // 0x801629B0

extern void InitSKingTriggers__Fv(); // 0x80162BF8

extern void InitSChambTriggers__Fv(); // 0x80162C44

extern void InitPWaterTriggers__Fv(); // 0x80162C90


#endif
