#ifndef STORM_H
#define STORM_H


extern void Enter__9CCritSect(struct CCritSect *this); // 0x8003DC3C


// decompiled code
// original method signature: 
// void /*$ra*/ Enter__9CCritSect(struct CCritSect *this /*$a0*/)
 // line 1104, offset 0x8003dc3c
	/* begin block 1 */
		// Start line: 1105
		// Start offset: 0x8003DC3C
	/* end block 1 */
	// End offset: 0x8003DC3C
	// End Line: 1105

	/* begin block 2 */
		// Start line: 2208
	/* end block 2 */
	// End Line: 2209

/* WARNING: Unknown calling convention yet parameter storage is locked */

void Enter__9CCritSect(CCritSect *this)

{
	return;
}





extern void * SMemAlloc(unsigned long bytes, char *filename, int linenumber, unsigned long flags); // 0x8007B1D0

extern unsigned char SMemFree(void *ptr, char *filename, int linenumber, unsigned long flags); // 0x8007B1F0


#endif
