#ifndef CREATURE_H
#define CREATURE_H


extern void * TryCreaturePrint__Fiiiiiii(int nMonster, int blockr, int blockg, int blockb, int OtPos, int ScrX, int ScrY); // 0x80093A28

extern void TryWater__FiiP8POLY_GT4i(int BlockBase, int BlockNum, struct POLY_GT4 *DestGt4, int MyOt); // 0x80093C8C

extern void nightgfx__FibiP8POLY_GT4i(int BlockBase, void * water, int BlockNum, struct POLY_GT4 *DestGt4, int MyOt); // 0x80093E64


#endif
