#ifndef DIALOG_H
#define DIALOG_H


extern struct Dialog * __6Dialog(struct Dialog *this); // 0x80083D30

extern struct Dialog * __6Dialog(struct Dialog *this); // 0x80093418

extern struct Dialog * __6Dialog(struct Dialog *this); // 0x80099A80

extern struct Dialog * __6Dialog(struct Dialog *this); // 0x8009A484

extern struct Dialog * __6Dialog(struct Dialog *this); // 0x8009E3C8

extern struct Dialog * __6Dialog(struct Dialog *this); // 0x80034F44

extern struct Dialog * __6Dialog(struct Dialog *this); // 0x80047AA4

extern struct Dialog * __6Dialog(struct Dialog *this); // 0x80063094

extern struct Dialog * __6Dialog(struct Dialog *this); // 0x8006D004

extern struct Dialog * __6Dialog(struct Dialog *this); // 0x8007B770

extern void _._6Dialog(struct Dialog *this, int __in_chrg); // 0x80083D08

extern void _._6Dialog(struct Dialog *this, int __in_chrg); // 0x800933F0

extern void _._6Dialog(struct Dialog *this, int __in_chrg); // 0x80099A58

extern void _._6Dialog(struct Dialog *this, int __in_chrg); // 0x8009A45C

extern void _._6Dialog(struct Dialog *this, int __in_chrg); // 0x8009E3A0

extern void _._6Dialog(struct Dialog *this, int __in_chrg); // 0x80034F1C

extern void _._6Dialog(struct Dialog *this, int __in_chrg); // 0x80047A7C

extern void _._6Dialog(struct Dialog *this, int __in_chrg); // 0x8006306C

extern void _._6Dialog(struct Dialog *this, int __in_chrg); // 0x8006CFDC

extern void _._6Dialog(struct Dialog *this, int __in_chrg); // 0x8007B748

extern int SetOTpos__6Dialogi(struct Dialog *this, int OT); // 0x800933E4

extern int SetOTpos__6Dialogi(struct Dialog *this, int OT); // 0x8009E394

extern void SetBorder__6Dialogi(struct Dialog *this, int Type); // 0x80083D00

extern void SetBorder__6Dialogi(struct Dialog *this, int Type); // 0x800933DC

extern void SetBorder__6Dialogi(struct Dialog *this, int Type); // 0x80099A50

extern void SetBorder__6Dialogi(struct Dialog *this, int Type); // 0x8009A454

extern void SetBorder__6Dialogi(struct Dialog *this, int Type); // 0x8009E38C

extern void SetBorder__6Dialogi(struct Dialog *this, int Type); // 0x80034F14

extern void SetBorder__6Dialogi(struct Dialog *this, int Type); // 0x80047A74

extern void SetBorder__6Dialogi(struct Dialog *this, int Type); // 0x80063064

extern void SetBorder__6Dialogi(struct Dialog *this, int Type); // 0x8006CFD4

extern void SetBorder__6Dialogi(struct Dialog *this, int Type); // 0x8007B740

extern void SetBack__6Dialogi(struct Dialog *this, int Type); // 0x80083CF8

extern void SetBack__6Dialogi(struct Dialog *this, int Type); // 0x80099A48

extern void SetBack__6Dialogi(struct Dialog *this, int Type); // 0x8009A44C

extern void SetBack__6Dialogi(struct Dialog *this, int Type); // 0x8009E384

extern void SetBack__6Dialogi(struct Dialog *this, int Type); // 0x80034F0C

extern void SetBack__6Dialogi(struct Dialog *this, int Type); // 0x8006305C

extern void SetBack__6Dialogi(struct Dialog *this, int Type); // 0x8007B738

extern void SetRGB__6DialogUcUcUc(struct Dialog *this, unsigned char R, unsigned char G, unsigned char B); // 0x80083CD8

extern void SetRGB__6DialogUcUcUc(struct Dialog *this, unsigned char R, unsigned char G, unsigned char B); // 0x800933BC

extern void SetRGB__6DialogUcUcUc(struct Dialog *this, unsigned char R, unsigned char G, unsigned char B); // 0x80099A28

extern void SetRGB__6DialogUcUcUc(struct Dialog *this, unsigned char R, unsigned char G, unsigned char B); // 0x8009A42C

extern void SetRGB__6DialogUcUcUc(struct Dialog *this, unsigned char R, unsigned char G, unsigned char B); // 0x8009E364

extern void SetRGB__6DialogUcUcUc(struct Dialog *this, unsigned char R, unsigned char G, unsigned char B); // 0x80034EEC

extern void SetRGB__6DialogUcUcUc(struct Dialog *this, unsigned char R, unsigned char G, unsigned char B); // 0x80047A54

extern void SetRGB__6DialogUcUcUc(struct Dialog *this, unsigned char R, unsigned char G, unsigned char B); // 0x8006303C

extern void SetRGB__6DialogUcUcUc(struct Dialog *this, unsigned char R, unsigned char G, unsigned char B); // 0x8006CFB4

extern void SetRGB__6DialogUcUcUc(struct Dialog *this, unsigned char R, unsigned char G, unsigned char B); // 0x8007B718


// decompiled code
// original method signature: 
// struct Dialog * /*$ra*/ __6Dialog(struct Dialog *this /*$v0*/)
 // line 60, offset 0x80083d30
	/* begin block 1 */
		// Start line: 61
		// Start offset: 0x80083D30
	/* end block 1 */
	// End offset: 0x80083D30
	// End Line: 61

	/* begin block 2 */
		// Start line: 120
	/* end block 2 */
	// End Line: 121

Dialog * __6Dialog(Dialog *this)

{
	this->BackGfx = 0xc6;
	this->BevelGfx = 0x30;
	this->BorderGfx = 0x30;
	DialogRed = -0x80;
	DialogGreen = -0x80;
	DialogBlue = -0x80;
	DialogTRed = ' ';
	DialogTGreen = ' ';
	DialogTBlue = ' ';
	this->DialogOTpos = 0xfa;
	return this;
}



// decompiled code
// original method signature: 
// struct Dialog * /*$ra*/ __6Dialog(struct Dialog *this /*$v0*/)
 // line 60, offset 0x80093418
	/* begin block 1 */
		// Start line: 61
		// Start offset: 0x80093418
	/* end block 1 */
	// End offset: 0x80093418
	// End Line: 61

	/* begin block 2 */
		// Start line: 120
	/* end block 2 */
	// End Line: 121

Dialog * __6Dialog(Dialog *this)

{
	this->BackGfx = 0xc6;
	this->BevelGfx = 0x30;
	this->BorderGfx = 0x30;
	DialogRed = -0x80;
	DialogGreen = -0x80;
	DialogBlue = -0x80;
	DialogTRed = ' ';
	DialogTGreen = ' ';
	DialogTBlue = ' ';
	this->DialogOTpos = 0xfa;
	return this;
}



// decompiled code
// original method signature: 
// struct Dialog * /*$ra*/ __6Dialog(struct Dialog *this /*$v0*/)
 // line 60, offset 0x80099a80
	/* begin block 1 */
		// Start line: 61
		// Start offset: 0x80099A80
	/* end block 1 */
	// End offset: 0x80099A80
	// End Line: 61

	/* begin block 2 */
		// Start line: 120
	/* end block 2 */
	// End Line: 121

Dialog * __6Dialog(Dialog *this)

{
	this->BackGfx = 0xc6;
	this->BevelGfx = 0x30;
	this->BorderGfx = 0x30;
	DialogRed = -0x80;
	DialogGreen = -0x80;
	DialogBlue = -0x80;
	DialogTRed = ' ';
	DialogTGreen = ' ';
	DialogTBlue = ' ';
	this->DialogOTpos = 0xfa;
	return this;
}



// decompiled code
// original method signature: 
// struct Dialog * /*$ra*/ __6Dialog(struct Dialog *this /*$v0*/)
 // line 60, offset 0x8009a484
	/* begin block 1 */
		// Start line: 61
		// Start offset: 0x8009A484
	/* end block 1 */
	// End offset: 0x8009A484
	// End Line: 61

	/* begin block 2 */
		// Start line: 120
	/* end block 2 */
	// End Line: 121

Dialog * __6Dialog(Dialog *this)

{
	this->BackGfx = 0xc6;
	this->BevelGfx = 0x30;
	this->BorderGfx = 0x30;
	DialogRed = -0x80;
	DialogGreen = -0x80;
	DialogBlue = -0x80;
	DialogTRed = ' ';
	DialogTGreen = ' ';
	DialogTBlue = ' ';
	this->DialogOTpos = 0xfa;
	return this;
}



// decompiled code
// original method signature: 
// struct Dialog * /*$ra*/ __6Dialog(struct Dialog *this /*$v0*/)
 // line 60, offset 0x8009e3c8
	/* begin block 1 */
		// Start line: 61
		// Start offset: 0x8009E3C8
	/* end block 1 */
	// End offset: 0x8009E3C8
	// End Line: 61

	/* begin block 2 */
		// Start line: 120
	/* end block 2 */
	// End Line: 121

Dialog * __6Dialog(Dialog *this)

{
	this->BackGfx = 0xc6;
	this->BevelGfx = 0x30;
	this->BorderGfx = 0x30;
	DialogRed = -0x80;
	DialogGreen = -0x80;
	DialogBlue = -0x80;
	DialogTRed = ' ';
	DialogTGreen = ' ';
	DialogTBlue = ' ';
	this->DialogOTpos = 0xfa;
	return this;
}



// decompiled code
// original method signature: 
// struct Dialog * /*$ra*/ __6Dialog(struct Dialog *this /*$v0*/)
 // line 60, offset 0x80034f44
	/* begin block 1 */
		// Start line: 61
		// Start offset: 0x80034F44
	/* end block 1 */
	// End offset: 0x80034F44
	// End Line: 61

	/* begin block 2 */
		// Start line: 120
	/* end block 2 */
	// End Line: 121

Dialog * __6Dialog(Dialog *this)

{
	this->BackGfx = 0xc6;
	this->BevelGfx = 0x30;
	this->BorderGfx = 0x30;
	DialogRed = -0x80;
	DialogGreen = -0x80;
	DialogBlue = -0x80;
	DialogTRed = ' ';
	DialogTGreen = ' ';
	DialogTBlue = ' ';
	this->DialogOTpos = 0xfa;
	return this;
}



// decompiled code
// original method signature: 
// struct Dialog * /*$ra*/ __6Dialog(struct Dialog *this /*$v0*/)
 // line 60, offset 0x80047aa4
	/* begin block 1 */
		// Start line: 61
		// Start offset: 0x80047AA4
	/* end block 1 */
	// End offset: 0x80047AA4
	// End Line: 61

	/* begin block 2 */
		// Start line: 120
	/* end block 2 */
	// End Line: 121

Dialog * __6Dialog(Dialog *this)

{
	this->BackGfx = 0xc6;
	this->BevelGfx = 0x30;
	this->BorderGfx = 0x30;
	DialogRed = -0x80;
	DialogGreen = -0x80;
	DialogBlue = -0x80;
	DialogTRed = ' ';
	DialogTGreen = ' ';
	DialogTBlue = ' ';
	this->DialogOTpos = 0xfa;
	return this;
}



// decompiled code
// original method signature: 
// struct Dialog * /*$ra*/ __6Dialog(struct Dialog *this /*$v0*/)
 // line 60, offset 0x80063094
	/* begin block 1 */
		// Start line: 61
		// Start offset: 0x80063094
	/* end block 1 */
	// End offset: 0x80063094
	// End Line: 61

	/* begin block 2 */
		// Start line: 120
	/* end block 2 */
	// End Line: 121

Dialog * __6Dialog(Dialog *this)

{
	this->BackGfx = 0xc6;
	this->BevelGfx = 0x30;
	this->BorderGfx = 0x30;
	DialogRed = -0x80;
	DialogGreen = -0x80;
	DialogBlue = -0x80;
	DialogTRed = ' ';
	DialogTGreen = ' ';
	DialogTBlue = ' ';
	this->DialogOTpos = 0xfa;
	return this;
}



// decompiled code
// original method signature: 
// struct Dialog * /*$ra*/ __6Dialog(struct Dialog *this /*$v0*/)
 // line 60, offset 0x8006d004
	/* begin block 1 */
		// Start line: 61
		// Start offset: 0x8006D004
	/* end block 1 */
	// End offset: 0x8006D004
	// End Line: 61

	/* begin block 2 */
		// Start line: 120
	/* end block 2 */
	// End Line: 121

Dialog * __6Dialog(Dialog *this)

{
	this->BackGfx = 0xc6;
	this->BevelGfx = 0x30;
	this->BorderGfx = 0x30;
	DialogRed = -0x80;
	DialogGreen = -0x80;
	DialogBlue = -0x80;
	DialogTRed = ' ';
	DialogTGreen = ' ';
	DialogTBlue = ' ';
	this->DialogOTpos = 0xfa;
	return this;
}



// decompiled code
// original method signature: 
// struct Dialog * /*$ra*/ __6Dialog(struct Dialog *this /*$v0*/)
 // line 60, offset 0x8007b770
	/* begin block 1 */
		// Start line: 61
		// Start offset: 0x8007B770
	/* end block 1 */
	// End offset: 0x8007B770
	// End Line: 61

	/* begin block 2 */
		// Start line: 120
	/* end block 2 */
	// End Line: 121

Dialog * __6Dialog(Dialog *this)

{
	this->BackGfx = 0xc6;
	this->BevelGfx = 0x30;
	this->BorderGfx = 0x30;
	DialogRed = -0x80;
	DialogGreen = -0x80;
	DialogBlue = -0x80;
	DialogTRed = ' ';
	DialogTGreen = ' ';
	DialogTBlue = ' ';
	this->DialogOTpos = 0xfa;
	return this;
}



// decompiled code
// original method signature: 
// void /*$ra*/ _._6Dialog(struct Dialog *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 77, offset 0x80083d08
	/* begin block 1 */
		// Start line: 78
		// Start offset: 0x80083D08
	/* end block 1 */
	// End offset: 0x80083D08
	// End Line: 78

	/* begin block 2 */
		// Start line: 154
	/* end block 2 */
	// End Line: 155

void ___6Dialog(Dialog *this,int __in_chrg)

{
	if ((__in_chrg & 1U) != 0) {
		__builtin_delete(this);
	}
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ _._6Dialog(struct Dialog *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 77, offset 0x800933f0
	/* begin block 1 */
		// Start line: 78
		// Start offset: 0x800933F0
	/* end block 1 */
	// End offset: 0x800933F0
	// End Line: 78

	/* begin block 2 */
		// Start line: 154
	/* end block 2 */
	// End Line: 155

void ___6Dialog(Dialog *this,int __in_chrg)

{
	if ((__in_chrg & 1U) != 0) {
		__builtin_delete(this);
	}
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ _._6Dialog(struct Dialog *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 77, offset 0x80099a58
	/* begin block 1 */
		// Start line: 78
		// Start offset: 0x80099A58
	/* end block 1 */
	// End offset: 0x80099A58
	// End Line: 78

	/* begin block 2 */
		// Start line: 154
	/* end block 2 */
	// End Line: 155

void ___6Dialog(Dialog *this,int __in_chrg)

{
	if ((__in_chrg & 1U) != 0) {
		__builtin_delete(this);
	}
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ _._6Dialog(struct Dialog *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 77, offset 0x8009a45c
	/* begin block 1 */
		// Start line: 78
		// Start offset: 0x8009A45C
	/* end block 1 */
	// End offset: 0x8009A45C
	// End Line: 78

	/* begin block 2 */
		// Start line: 154
	/* end block 2 */
	// End Line: 155

void ___6Dialog(Dialog *this,int __in_chrg)

{
	if ((__in_chrg & 1U) != 0) {
		__builtin_delete(this);
	}
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ _._6Dialog(struct Dialog *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 77, offset 0x8009e3a0
	/* begin block 1 */
		// Start line: 78
		// Start offset: 0x8009E3A0
	/* end block 1 */
	// End offset: 0x8009E3A0
	// End Line: 78

	/* begin block 2 */
		// Start line: 154
	/* end block 2 */
	// End Line: 155

void ___6Dialog(Dialog *this,int __in_chrg)

{
	if ((__in_chrg & 1U) != 0) {
		__builtin_delete(this);
	}
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ _._6Dialog(struct Dialog *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 77, offset 0x80034f1c
	/* begin block 1 */
		// Start line: 78
		// Start offset: 0x80034F1C
	/* end block 1 */
	// End offset: 0x80034F1C
	// End Line: 78

	/* begin block 2 */
		// Start line: 154
	/* end block 2 */
	// End Line: 155

void ___6Dialog(Dialog *this,int __in_chrg)

{
	if ((__in_chrg & 1U) != 0) {
		__builtin_delete(this);
	}
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ _._6Dialog(struct Dialog *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 77, offset 0x80047a7c
	/* begin block 1 */
		// Start line: 78
		// Start offset: 0x80047A7C
	/* end block 1 */
	// End offset: 0x80047A7C
	// End Line: 78

	/* begin block 2 */
		// Start line: 154
	/* end block 2 */
	// End Line: 155

void ___6Dialog(Dialog *this,int __in_chrg)

{
	if ((__in_chrg & 1U) != 0) {
		__builtin_delete(this);
	}
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ _._6Dialog(struct Dialog *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 77, offset 0x8006306c
	/* begin block 1 */
		// Start line: 78
		// Start offset: 0x8006306C
	/* end block 1 */
	// End offset: 0x8006306C
	// End Line: 78

	/* begin block 2 */
		// Start line: 154
	/* end block 2 */
	// End Line: 155

void ___6Dialog(Dialog *this,int __in_chrg)

{
	if ((__in_chrg & 1U) != 0) {
		__builtin_delete(this);
	}
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ _._6Dialog(struct Dialog *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 77, offset 0x8006cfdc
	/* begin block 1 */
		// Start line: 78
		// Start offset: 0x8006CFDC
	/* end block 1 */
	// End offset: 0x8006CFDC
	// End Line: 78

	/* begin block 2 */
		// Start line: 154
	/* end block 2 */
	// End Line: 155

void ___6Dialog(Dialog *this,int __in_chrg)

{
	if ((__in_chrg & 1U) != 0) {
		__builtin_delete(this);
	}
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ _._6Dialog(struct Dialog *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 77, offset 0x8007b748
	/* begin block 1 */
		// Start line: 78
		// Start offset: 0x8007B748
	/* end block 1 */
	// End offset: 0x8007B748
	// End Line: 78

	/* begin block 2 */
		// Start line: 154
	/* end block 2 */
	// End Line: 155

void ___6Dialog(Dialog *this,int __in_chrg)

{
	if ((__in_chrg & 1U) != 0) {
		__builtin_delete(this);
	}
	return;
}



// decompiled code
// original method signature: 
// int /*$ra*/ SetOTpos__6Dialogi(struct Dialog *this /*$a0*/, int OT /*$a1*/)
 // line 84, offset 0x800933e4
	/* begin block 1 */
		// Start line: 85
		// Start offset: 0x800933E4
		// Variables:
	// 		int OldOT; // $v0
	/* end block 1 */
	// End offset: 0x800933E8
	// End Line: 88

	/* begin block 2 */
		// Start line: 169
	/* end block 2 */
	// End Line: 170

int SetOTpos__6Dialogi(Dialog *this,int OT)

{
	int iVar1;
	
	iVar1 = this->DialogOTpos;
	this->DialogOTpos = OT;
	return iVar1;
}



// decompiled code
// original method signature: 
// int /*$ra*/ SetOTpos__6Dialogi(struct Dialog *this /*$a0*/, int OT /*$a1*/)
 // line 84, offset 0x8009e394
	/* begin block 1 */
		// Start line: 85
		// Start offset: 0x8009E394
		// Variables:
	// 		int OldOT; // $v0
	/* end block 1 */
	// End offset: 0x8009E398
	// End Line: 88

	/* begin block 2 */
		// Start line: 169
	/* end block 2 */
	// End Line: 170

int SetOTpos__6Dialogi(Dialog *this,int OT)

{
	int iVar1;
	
	iVar1 = this->DialogOTpos;
	this->DialogOTpos = OT;
	return iVar1;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBorder__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 94, offset 0x80083d00
	/* begin block 1 */
		// Start line: 95
		// Start offset: 0x80083D00
	/* end block 1 */
	// End offset: 0x80083D00
	// End Line: 95

	/* begin block 2 */
		// Start line: 188
	/* end block 2 */
	// End Line: 189

void SetBorder__6Dialogi(Dialog *this,int Type)

{
	this->BorderGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBorder__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 94, offset 0x800933dc
	/* begin block 1 */
		// Start line: 95
		// Start offset: 0x800933DC
	/* end block 1 */
	// End offset: 0x800933DC
	// End Line: 95

	/* begin block 2 */
		// Start line: 188
	/* end block 2 */
	// End Line: 189

void SetBorder__6Dialogi(Dialog *this,int Type)

{
	this->BorderGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBorder__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 94, offset 0x80099a50
	/* begin block 1 */
		// Start line: 95
		// Start offset: 0x80099A50
	/* end block 1 */
	// End offset: 0x80099A50
	// End Line: 95

	/* begin block 2 */
		// Start line: 188
	/* end block 2 */
	// End Line: 189

void SetBorder__6Dialogi(Dialog *this,int Type)

{
	this->BorderGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBorder__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 94, offset 0x8009a454
	/* begin block 1 */
		// Start line: 95
		// Start offset: 0x8009A454
	/* end block 1 */
	// End offset: 0x8009A454
	// End Line: 95

	/* begin block 2 */
		// Start line: 188
	/* end block 2 */
	// End Line: 189

void SetBorder__6Dialogi(Dialog *this,int Type)

{
	this->BorderGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBorder__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 94, offset 0x8009e38c
	/* begin block 1 */
		// Start line: 95
		// Start offset: 0x8009E38C
	/* end block 1 */
	// End offset: 0x8009E38C
	// End Line: 95

	/* begin block 2 */
		// Start line: 188
	/* end block 2 */
	// End Line: 189

void SetBorder__6Dialogi(Dialog *this,int Type)

{
	this->BorderGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBorder__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 94, offset 0x80034f14
	/* begin block 1 */
		// Start line: 95
		// Start offset: 0x80034F14
	/* end block 1 */
	// End offset: 0x80034F14
	// End Line: 95

	/* begin block 2 */
		// Start line: 188
	/* end block 2 */
	// End Line: 189

void SetBorder__6Dialogi(Dialog *this,int Type)

{
	this->BorderGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBorder__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 94, offset 0x80047a74
	/* begin block 1 */
		// Start line: 95
		// Start offset: 0x80047A74
	/* end block 1 */
	// End offset: 0x80047A74
	// End Line: 95

	/* begin block 2 */
		// Start line: 188
	/* end block 2 */
	// End Line: 189

void SetBorder__6Dialogi(Dialog *this,int Type)

{
	this->BorderGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBorder__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 94, offset 0x80063064
	/* begin block 1 */
		// Start line: 95
		// Start offset: 0x80063064
	/* end block 1 */
	// End offset: 0x80063064
	// End Line: 95

	/* begin block 2 */
		// Start line: 188
	/* end block 2 */
	// End Line: 189

void SetBorder__6Dialogi(Dialog *this,int Type)

{
	this->BorderGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBorder__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 94, offset 0x8006cfd4
	/* begin block 1 */
		// Start line: 95
		// Start offset: 0x8006CFD4
	/* end block 1 */
	// End offset: 0x8006CFD4
	// End Line: 95

	/* begin block 2 */
		// Start line: 188
	/* end block 2 */
	// End Line: 189

void SetBorder__6Dialogi(Dialog *this,int Type)

{
	this->BorderGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBorder__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 94, offset 0x8007b740
	/* begin block 1 */
		// Start line: 95
		// Start offset: 0x8007B740
	/* end block 1 */
	// End offset: 0x8007B740
	// End Line: 95

	/* begin block 2 */
		// Start line: 188
	/* end block 2 */
	// End Line: 189

void SetBorder__6Dialogi(Dialog *this,int Type)

{
	this->BorderGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBack__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 97, offset 0x80083cf8
	/* begin block 1 */
		// Start line: 98
		// Start offset: 0x80083CF8
	/* end block 1 */
	// End offset: 0x80083CF8
	// End Line: 98

	/* begin block 2 */
		// Start line: 194
	/* end block 2 */
	// End Line: 195

void SetBack__6Dialogi(Dialog *this,int Type)

{
	this->BackGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBack__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 97, offset 0x80099a48
	/* begin block 1 */
		// Start line: 98
		// Start offset: 0x80099A48
	/* end block 1 */
	// End offset: 0x80099A48
	// End Line: 98

	/* begin block 2 */
		// Start line: 194
	/* end block 2 */
	// End Line: 195

void SetBack__6Dialogi(Dialog *this,int Type)

{
	this->BackGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBack__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 97, offset 0x8009a44c
	/* begin block 1 */
		// Start line: 98
		// Start offset: 0x8009A44C
	/* end block 1 */
	// End offset: 0x8009A44C
	// End Line: 98

	/* begin block 2 */
		// Start line: 194
	/* end block 2 */
	// End Line: 195

void SetBack__6Dialogi(Dialog *this,int Type)

{
	this->BackGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBack__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 97, offset 0x8009e384
	/* begin block 1 */
		// Start line: 98
		// Start offset: 0x8009E384
	/* end block 1 */
	// End offset: 0x8009E384
	// End Line: 98

	/* begin block 2 */
		// Start line: 194
	/* end block 2 */
	// End Line: 195

void SetBack__6Dialogi(Dialog *this,int Type)

{
	this->BackGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBack__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 97, offset 0x80034f0c
	/* begin block 1 */
		// Start line: 98
		// Start offset: 0x80034F0C
	/* end block 1 */
	// End offset: 0x80034F0C
	// End Line: 98

	/* begin block 2 */
		// Start line: 194
	/* end block 2 */
	// End Line: 195

void SetBack__6Dialogi(Dialog *this,int Type)

{
	this->BackGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBack__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 97, offset 0x8006305c
	/* begin block 1 */
		// Start line: 98
		// Start offset: 0x8006305C
	/* end block 1 */
	// End offset: 0x8006305C
	// End Line: 98

	/* begin block 2 */
		// Start line: 194
	/* end block 2 */
	// End Line: 195

void SetBack__6Dialogi(Dialog *this,int Type)

{
	this->BackGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBack__6Dialogi(struct Dialog *this /*$a0*/, int Type /*$a1*/)
 // line 97, offset 0x8007b738
	/* begin block 1 */
		// Start line: 98
		// Start offset: 0x8007B738
	/* end block 1 */
	// End offset: 0x8007B738
	// End Line: 98

	/* begin block 2 */
		// Start line: 194
	/* end block 2 */
	// End Line: 195

void SetBack__6Dialogi(Dialog *this,int Type)

{
	this->BackGfx = Type;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetRGB__6DialogUcUcUc(struct Dialog *this /*$a0*/, unsigned char R /*$a1*/, unsigned char G /*$a2*/, unsigned char B /*$a3*/)
 // line 102, offset 0x80083cd8
	/* begin block 1 */
		// Start line: 103
		// Start offset: 0x80083CD8
	/* end block 1 */
	// End offset: 0x80083CF0
	// End Line: 106

	/* begin block 2 */
		// Start line: 205
	/* end block 2 */
	// End Line: 206

void SetRGB__6DialogUcUcUc(Dialog *this,uchar R,uchar G,uchar B)

{
	DialogRed = R;
	DialogGreen = G;
	DialogBlue = B;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetRGB__6DialogUcUcUc(struct Dialog *this /*$a0*/, unsigned char R /*$a1*/, unsigned char G /*$a2*/, unsigned char B /*$a3*/)
 // line 102, offset 0x800933bc
	/* begin block 1 */
		// Start line: 103
		// Start offset: 0x800933BC
	/* end block 1 */
	// End offset: 0x800933D4
	// End Line: 106

	/* begin block 2 */
		// Start line: 205
	/* end block 2 */
	// End Line: 206

void SetRGB__6DialogUcUcUc(Dialog *this,uchar R,uchar G,uchar B)

{
	DialogRed = R;
	DialogGreen = G;
	DialogBlue = B;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetRGB__6DialogUcUcUc(struct Dialog *this /*$a0*/, unsigned char R /*$a1*/, unsigned char G /*$a2*/, unsigned char B /*$a3*/)
 // line 102, offset 0x80099a28
	/* begin block 1 */
		// Start line: 103
		// Start offset: 0x80099A28
	/* end block 1 */
	// End offset: 0x80099A40
	// End Line: 106

	/* begin block 2 */
		// Start line: 205
	/* end block 2 */
	// End Line: 206

void SetRGB__6DialogUcUcUc(Dialog *this,uchar R,uchar G,uchar B)

{
	DialogRed = R;
	DialogGreen = G;
	DialogBlue = B;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetRGB__6DialogUcUcUc(struct Dialog *this /*$a0*/, unsigned char R /*$a1*/, unsigned char G /*$a2*/, unsigned char B /*$a3*/)
 // line 102, offset 0x8009a42c
	/* begin block 1 */
		// Start line: 103
		// Start offset: 0x8009A42C
	/* end block 1 */
	// End offset: 0x8009A444
	// End Line: 106

	/* begin block 2 */
		// Start line: 205
	/* end block 2 */
	// End Line: 206

void SetRGB__6DialogUcUcUc(Dialog *this,uchar R,uchar G,uchar B)

{
	DialogRed = R;
	DialogGreen = G;
	DialogBlue = B;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetRGB__6DialogUcUcUc(struct Dialog *this /*$a0*/, unsigned char R /*$a1*/, unsigned char G /*$a2*/, unsigned char B /*$a3*/)
 // line 102, offset 0x8009e364
	/* begin block 1 */
		// Start line: 103
		// Start offset: 0x8009E364
	/* end block 1 */
	// End offset: 0x8009E37C
	// End Line: 106

	/* begin block 2 */
		// Start line: 205
	/* end block 2 */
	// End Line: 206

void SetRGB__6DialogUcUcUc(Dialog *this,uchar R,uchar G,uchar B)

{
	DialogRed = R;
	DialogGreen = G;
	DialogBlue = B;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetRGB__6DialogUcUcUc(struct Dialog *this /*$a0*/, unsigned char R /*$a1*/, unsigned char G /*$a2*/, unsigned char B /*$a3*/)
 // line 102, offset 0x80034eec
	/* begin block 1 */
		// Start line: 103
		// Start offset: 0x80034EEC
	/* end block 1 */
	// End offset: 0x80034F04
	// End Line: 106

	/* begin block 2 */
		// Start line: 205
	/* end block 2 */
	// End Line: 206

void SetRGB__6DialogUcUcUc(Dialog *this,uchar R,uchar G,uchar B)

{
	DialogRed = R;
	DialogGreen = G;
	DialogBlue = B;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetRGB__6DialogUcUcUc(struct Dialog *this /*$a0*/, unsigned char R /*$a1*/, unsigned char G /*$a2*/, unsigned char B /*$a3*/)
 // line 102, offset 0x80047a54
	/* begin block 1 */
		// Start line: 103
		// Start offset: 0x80047A54
	/* end block 1 */
	// End offset: 0x80047A6C
	// End Line: 106

	/* begin block 2 */
		// Start line: 205
	/* end block 2 */
	// End Line: 206

void SetRGB__6DialogUcUcUc(Dialog *this,uchar R,uchar G,uchar B)

{
	DialogRed = R;
	DialogGreen = G;
	DialogBlue = B;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetRGB__6DialogUcUcUc(struct Dialog *this /*$a0*/, unsigned char R /*$a1*/, unsigned char G /*$a2*/, unsigned char B /*$a3*/)
 // line 102, offset 0x8006303c
	/* begin block 1 */
		// Start line: 103
		// Start offset: 0x8006303C
	/* end block 1 */
	// End offset: 0x80063054
	// End Line: 106

	/* begin block 2 */
		// Start line: 205
	/* end block 2 */
	// End Line: 206

void SetRGB__6DialogUcUcUc(Dialog *this,uchar R,uchar G,uchar B)

{
	DialogRed = R;
	DialogGreen = G;
	DialogBlue = B;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetRGB__6DialogUcUcUc(struct Dialog *this /*$a0*/, unsigned char R /*$a1*/, unsigned char G /*$a2*/, unsigned char B /*$a3*/)
 // line 102, offset 0x8006cfb4
	/* begin block 1 */
		// Start line: 103
		// Start offset: 0x8006CFB4
	/* end block 1 */
	// End offset: 0x8006CFCC
	// End Line: 106

	/* begin block 2 */
		// Start line: 205
	/* end block 2 */
	// End Line: 206

void SetRGB__6DialogUcUcUc(Dialog *this,uchar R,uchar G,uchar B)

{
	DialogRed = R;
	DialogGreen = G;
	DialogBlue = B;
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetRGB__6DialogUcUcUc(struct Dialog *this /*$a0*/, unsigned char R /*$a1*/, unsigned char G /*$a2*/, unsigned char B /*$a3*/)
 // line 102, offset 0x8007b718
	/* begin block 1 */
		// Start line: 103
		// Start offset: 0x8007B718
	/* end block 1 */
	// End offset: 0x8007B730
	// End Line: 106

	/* begin block 2 */
		// Start line: 205
	/* end block 2 */
	// End Line: 206

void SetRGB__6DialogUcUcUc(Dialog *this,uchar R,uchar G,uchar B)

{
	DialogRed = R;
	DialogGreen = G;
	DialogBlue = B;
	return;
}





extern unsigned char TrimCol__Fs(short col); // 0x800850B4

extern struct POLY_GT4 * DialogPrint__Fiiiiiiiiii(int Frm, int X, int Y, int SW, int SH, int UW, int UH, int UOfs, int VOfs, int Trans); // 0x800850EC

extern struct POLY_G4 * GetDropShadowG4__FUcUcUcUcUcUcUcUcUcUcUcUc(unsigned char r0, unsigned char g0, unsigned char b0, unsigned char r1, int g1, int b1, int r2, int g2, int b2, int r3, int g3, int b3); // 0x80085A64

extern void DropShadows__Fiiii(int x, int y, int w, int h); // 0x80085B9C

extern void InitDialog__Fv(); // 0x80085E40

extern void GetSizes__6Dialog(struct Dialog *this); // 0x80085F78

extern void Back__6Dialogiiii(struct Dialog *this, int DX, int DY, int DW, int DH); // 0x800861D0

extern void Line__6Dialogiii(struct Dialog *this, int DX, int DY, int DW); // 0x80087390


#endif
