#include "THISDUST.H"
#include "GAMEONLY.H"


// decompiled code
// original method signature: 
// void /*$ra*/ GameOnlyTestRoutine__Fv()
 // line 63, offset 0x80137684
	/* begin block 1 */
		// Start line: 64
		// Start offset: 0x80137684
	/* end block 1 */
	// End offset: 0x80137684
	// End Line: 64

	/* begin block 2 */
		// Start line: 129
	/* end block 2 */
	// End Line: 130

/* WARNING: Unknown calling convention yet parameter storage is locked */

void GameOnlyTestRoutine__Fv(void)

{
	return;
}





