#include "THISDUST.H"
#include "LAMBO.H"


// decompiled code
// original method signature: 
// void /*$ra*/ StevesDummyPoll__Fv()
 // line 74, offset 0x8008c03c
	/* begin block 1 */
		// Start line: 75
		// Start offset: 0x8008C03C
	/* end block 1 */
	// End offset: 0x8008C03C
	// End Line: 75

	/* begin block 2 */
		// Start line: 149
	/* end block 2 */
	// End Line: 150

/* WARNING: Unknown calling convention yet parameter storage is locked */

void StevesDummyPoll__Fv(void)

{
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ Lambo__Fv()
 // line 78, offset 0x8008c044
	/* begin block 1 */
		// Start line: 79
		// Start offset: 0x8008C044
	/* end block 1 */
	// End offset: 0x8008C044
	// End Line: 80

	/* begin block 2 */
		// Start line: 159
	/* end block 2 */
	// End Line: 160

/* WARNING: Unknown calling convention yet parameter storage is locked */

void Lambo__Fv(void)

{
	return;
}





