#include "THISDUST.H"
#include "MEM.H"


// decompiled code
// original method signature: 
// void /*$ra*/ MyFilter__FUlUlPCc(unsigned long MemType /*$a0*/, unsigned long Size /*$a1*/, char *Name /*$a2*/)
 // line 96, offset 0x8007ca14
	/* begin block 1 */
		// Start line: 97
		// Start offset: 0x8007CA14
	/* end block 1 */
	// End offset: 0x8007CA14
	// End Line: 97

void MyFilter__FUlUlPCc(ulong MemType,ulong Size,char *Name)

{
	return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SlowMemMove__FPvT0Ul(void *Dest /*$a0*/, void *Source /*$a1*/, unsigned long size /*$a2*/)
 // line 148, offset 0x8007ca1c
	/* begin block 1 */
		// Start line: 149
		// Start offset: 0x8007CA1C
	/* end block 1 */
	// End offset: 0x8007CA2C
	// End Line: 150

	/* begin block 2 */
		// Start line: 296
	/* end block 2 */
	// End Line: 297

void SlowMemMove__FPvT0Ul(void *Dest,void *Source,ulong size)

{
	memmove(Dest,Source,size);
	return;
}





